version: '3'
services:
  web:
    restart: always
    image: nginx
  proxy:
    restart: always
    build:
      context: ../../
      dockerfile: ./Dockerfile
      target: tls13zig_proxy
    volumes:
      - "../../test-certs:/certs:ro"
    ports:
      - 8443:8443
    environment:
      - PROXY_TLS_KEYFILE=/certs/key.pem
      - PROXY_TLS_CERTFILE=/certs/cert.pem
      - PROXY_TLS_CAFILE=/certs/chain.pem
      - PROXY_TLS_HOSTNAME=localhost
      - PROXY_BIND_PORT=8443
      - PROXY_UPSTREAM_HOST=web
      - PROXY_UPSTREAM_PORT=80