name: CI

on: push

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check *.zig src/*.zig

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig build test
  
  e2e-test-with-openssl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          tags: zig-master
          push: false
          load: true
          cache-from: type=gha,scope=buildx-${{ github.workflow }}-${{ github.job }}
          cache-to: type=gha,mode=max,scope=buildx-${{ github.workflow }}-${{ github.job }}

      - uses: addnab/docker-run-action@v3
        with:
          image: zig-master
          run: /tls13-zig/test.sh